### PR TITLE
Clear token on logout

### LINKED ISSUE #184: RedditClient#deauthenticate() doesn't clear the stored access tokens
Please correct me if I'm doing this wrong, but looks like the access tokens stored in a `TokenHandler` never get cleared because `RedditClient#deauthenticate()` never notifies `AuthenticationManager` about it. As a result, when a new `RedditClient` object is created (e.g., when the app restarts), the user is logged back in because we still have the access token.

I will send a PR soon. Please feel free to reject it if this is incorrect.

**Update:** My PR is ready, but it's blocked on #183. You can view it separately here in the meanwhile: https://github.com/Saketme/JRAW/pull/2

### PR DESCRIPTION
**Pull request by Saketme**
Fixes #184

### CODE REVIEW

File: src/main/java/net/dean/jraw/auth/AuthenticationManager.java [hunk 1]
```diff
@@ -108,12 +113,21 @@ public void refreshAccessToken(Credentials credentials) throws NoSuchTokenExcept
...
+        // Refresh token is only received when authenticating for the first time.
+        // Subsequent calls for refreshing the token don't receive the refresh
+        // token again.
         if (o.getRefreshToken() != null) {
             tokenHandler.writeToken(getUsername(), o.getRefreshToken());
         }
         tokenHandler.writeAcquireTimeMillis(getUsername(), System.currentTimeMillis());
     }
 
+    private void onDeAuthenticated() {
```
Comment (thatJavaNerd) [inline src/main/java/net/dean/jraw/auth/AuthenticationManager.java]: Let's change this to `onDeauthenticated()` like above

Comment (Saketme) [inline src/main/java/net/dean/jraw/auth/AuthenticationManager.java]: Whoops, fixed.

**Comment by thatJavaNerd** [comment]
Looks good, thanks!
